apiVersion: v1
data:
  hosts: |+
    127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
    ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

  key1: value1
  key2: value2
kind: ConfigMap
metadata:
  name: datacm
