
apiVersion: v1
kind: LimitRange
metadata:
  name: memory-resource-limit
  namespace: test-resource-mgmt

spec:
  limits:
  - default: # this section defines default limits
      memory: 500Mi
    defaultRequest: # this section defines default requests
      memory: 200Mi
    max: # max and min define the limit range
      memory: 1Gi
    min:
      memory: 100Mi
    type: Container


