apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: web
  name: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: mjbright/k8s-demo:1
        name: k8s-demo
