apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-01-25T12:54:05Z"
  labels:
    app: web
  name: web2
  namespace: default
  resourceVersion: "67557"
  uid: 5646adde-76d0-475c-b0dc-02c00dfe993e
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
