apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo
  name: demo
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: demo
    release: demo
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: demo
  name: demo
spec:
  minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app: demo
      release: demo
  template:
    metadata:
      labels:
        app: demo
        release: demo
    spec:
      containers:
      - image: scraly/test.dockerapp:latest
        name: demo
      imagePullSecrets:
      - name: regsecret-dev
