apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    app.kubernetes.io/managed-by: Helm
  annotations:
      meta.helm.sh/release-name: v8.0
      meta.helm.sh/release-namespace: default

spec:
  type: LoadBalancer
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379

  selector:
    app: redis
