apiVersion: v1
kind: Pod
metadata:
  labels:
    run: simplepod
    owner: mike
  name: simplepod
spec:

  initContainers:
  - image: alpine
    name: init1
    command: ['wget', '-qO', '-', 'google.com']

  - image: alpine
    name: init2
    command: ['/bin/sh', '-c', 'touch /tmp/ready; touch /tmp/live']
    volumeMounts:
    - name: ed
      mountPath: /tmp

  containers:
  - image: nginx:1.18
    name: simplepod
    volumeMounts:
    - name: ed
      mountPath: /tmp

    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/ready
      initialDelaySeconds: 5
      periodSeconds: 5

    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/live
      initialDelaySeconds: 5
      periodSeconds: 5

  volumes:
    - name: ed
      emptyDir: {}



