apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simpledeploy
  name: simpledeploy
spec:

  replicas: 3
  selector:
    matchLabels:
      app: simpledeploy
  template:
    metadata:
      labels:
        app: simpledeploy
    spec:

      containers:
      - image: nginx:1.18
        name: simplepod

    
