apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: webserv
  name: webserv
spec:
  containers:
  - image: nginx:1.18
    name: webserv
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
