apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kdemo
  name: web-svc-headless
spec:
  type: ClusterIP
  clusterIP: None

  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: kdemo
