apiVersion: v1
kind: Pod
metadata:
  labels:
    run: containers
  name: containers
spec:
  containers:
  - image: alpine
    name: containers
    command: ['/bin/sh', '-c', 'while true; do cd /tmp/ed; date >> container.date.log; sleep 1; done']

    volumeMounts:
    - name: ed
      mountPath: /tmp/ed

  - image: alpine
    name: containers-2
    command: ['/bin/sh', '-c', 'while true; do cd /tmp/ed; cat container.date.log; sleep 1; done']

    volumeMounts:
    - name: ed
      mountPath: /tmp/ed

  volumes:
  - name: ed
    emptyDir: {}
