apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: netpol-01
  labels:
    app: web
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
---
apiVersion: v1
kind: Pod
metadata:
  name: web
  namespace: netpol-01
  labels:
    app: web
spec:
  containers:
  - image: nginx
    name: web
    ports:
    - containerPort: 80
