apiVersion: v1
kind: Pod
metadata:
  labels:
    run: webserv
  name: webserv
spec:
  initContainers:
  - image: alpine:latest
    name:  init1
    command: ['/bin/sh','-c','wget -qO - https://google.com/']
  - image: alpine:latest
    name:  init2
    command: ['/bin/sh','-c','touch /tmp/ready; touch /tmp/live']
  containers:
  - image: nginx:1.18
    name: webserv
