apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zonedeploy
  name: zonedeploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zonedeploy
  template:
    metadata:
      labels:
        app: zonedeploy
    spec:
      containers:
      - image: nginx
        name: nginx

      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: usage
                operator: In
                values:
                - Prod
            topologyKey: zone


