apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webserv
  name: webserv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webserv
    spec:
      containers:
      - image: nginx:1.18
        name: nginx
        resources: {}
status: {}
