apiVersion: v1
kind: Service

metadata:
  name: flask-fe
  labels:
    app: flask-fe

spec:
  type: LoadBalancer

  ports:
  - port: 9001
    protocol: TCP
    targetPort: 9001

  selector:
    app: flask-fe
