apiVersion: v1
kind: Namespace
metadata:
  name: singlepod
---
apiVersion: v1
kind: Pod
metadata:
  namespace: singlepod
  labels:
    run: singlepod
  name: singlepod-1c
spec:
  #shareProcessNamespace: true
  containers:
  - image: mjbright/k8s-demo:1
    name: c1
  - image: mjbright/k8s-demo:alpine1
    name: c2
    command: ['/bin/sleep', 'infinity']
    

