apiVersion: v1
kind: Pod
metadata:
  name: testpod
  labels:
    run: testpod

spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - 'while true; do echo "$(date): $( cat /mnt/cm/key1)"; sleep 5; done'
    image: alpine
    name: testpod

    volumeMounts:
    - name: configmap
      mountPath: /mnt/cm

  volumes:
  - name: configmap
    configMap:
      name: cm1
