
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: noping
  name: noping
spec:
  containers:
  - image: alpine
    name: noping
    command: ["/bin/sleep", "36000"]
    securityContext:
      capabilities:
        drop: ["NET_RAW"]
        
