apiVersion: v1
kind: Namespace
metadata:
  name: singlepod
---
apiVersion: v1
kind: Pod
metadata:
  namespace: singlepod
  labels:
    run: singlepod
  name: singlepod
spec:
  initContainers:
  - image: alpine
    name:  init1
    command: ['/bin/sh', '-c', 'sleep 5; /bin/echo init1 started > /vol/empty1/init1.start']
    volumeMounts:
    - name: empty1
      mountPath: /vol/empty1

  - image: alpine
    name:  init2
    command: ['/bin/sh', '-c', 'sleep 5; /bin/echo init2 started > /vol/empty1/init2.start']
    volumeMounts:
    - name: empty1
      mountPath: /vol/empty1
  
  containers:
  - image: alpine
    name: singlepod
    command: ['/bin/sh', '-c', 'cat /vol/init2/init1.start /vol/init2/init2.start']
    volumeMounts:
    - name: empty1
      mountPath: /vol/init2

  volumes:
  - emptyDir: {}
    name:     empty1
    

