apiVersion: v1
kind: Namespace
metadata:
  name: logger
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: logger
  name: logger
  namespace: logger

spec:
  selector:
    matchLabels:
      app: logger
  template:
    metadata:
      labels:
        app: logger
    spec:
      containers:
      - image: alpine
        name: alpine
        command: ['/bin/sh', '-c', 'while true; do echo "-- $( date ) --------"; ls -altrH /var/log/containers/*alpine*; sleep 1; done']
        volumeMounts:
        - name: host
          mountPath: /var/log

      volumes:
      - name: host
        hostPath:
          path: /var/log

