apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web1
  name: web1

spec:
  replicas: 3
  selector:
    matchLabels:
      app: web1

  template:
    metadata:
      labels:
        app: web1

    spec:
      containers:
      - image: mjbright/k8s-demo:1
        name: k8s-demo
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web1
  name: web1

spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80

  selector:
    app: web1

