apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web2
  name: web2

spec:
  replicas: 3
  selector:
    matchLabels:
      app: web2

  template:
    metadata:
      labels:
        app: web2

    spec:
      containers:
      - image: mjbright/k8s-demo:2
        name: k8s-demo
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web2
  name: web2

spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80

  selector:
    app: web2

