apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-list-all
roleRef:
  kind: ClusterRole
  name: secret-list-all
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  # Allow all (authenticated) users:
  name: system:authenticated
  apiGroup: rbac.authorization.k8s.io

# NO: Don't allow UN-authenticated users:
# - kind: Group
#   name: system:unauthenticated
#   apiGroup: rbac.authorization.k8s.io
