apiVersion: v1
kind: Pod
metadata:
  labels:
    run: init-cont
  name: init-cont
  namespace: test2

spec:
  initContainers:
  - image: mjbright/k8s-demo:alpine1
    name: init-1
    command: ['/bin/sh', '-c', 'echo "init-1: $(date) Waiting for Godot"; sleep 5']
  - image: mjbright/k8s-demo:alpine1
    name: init-2
    command: ['/bin/sh', '-c', 'echo "init-2: $(date) Waiting for Godot"; sleep 5']

  containers:
  - image: mjbright/k8s-demo:alpine1
    name: demo-1
    command: ['/bin/sh', '-c', 'echo "demo-1: $(date) going to sleep ..."; sleep infinity']

  - image: mjbright/k8s-demo:alpine1
    name: demo-2
    command: ['/bin/sh', '-c', 'echo "demo-2: $(date) going to sleep ..."; sleep infinity']

  - image: mjbright/k8s-demo:alpine1
    name: demo-3
    command:
    - /bin/sleep
    - infinity

  - image: mjbright/k8s-demo:alpine1
    name: demo-4
    command: ['/bin/sleep','infinity']

    # command: ['/bin/bash', '-c', 
    # 'echo "demo-2: $(date) going to sleep ..."; sleep infinity'
    # ]



