apiVersion: v1
kind: Pod
metadata:
  labels:
    run: testpod3
  name: testpod3
  namespace: test2

spec:
  shareProcessNamespace: true

  containers:
  - image: mjbright/k8s-demo:alpine1
    name: testpod3-1

  - image: mjbright/k8s-demo:alpine1
    name: testpod3-2
    command: ['/bin/sleep', 'infinity']


