apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask-app
  name: flask-app

spec:
  replicas: 8
  selector:
    matchLabels:
      app: flask-app

  template:
    metadata:
      labels:
        app: flask-app

    spec:
      containers:
      - image: mjbright/flask-web:v2
        imagePullPolicy: Always
        name: flask-app
        ports:
        - containerPort: 5000

