apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask-webfe
  name: flask-webfe

spec:
  replicas: 8
  selector:
    matchLabels:
      app: flask-webfe

  template:
    metadata:
      labels:
        app: flask-webfe

    spec:
      containers:
      - image: mjbright/flask-web:v2
        imagePullPolicy: Always
        name: flask-webfe
        ports:
        - containerPort: 5000

