kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv5
  labels:
    type: local
spec:
  storageClassName: ssd
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/pv5
