apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask-app
  name: flask-app

spec:
  type: LoadBalancer
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000

  selector:
    app: flask-app
