kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv6
  labels:
    type: local
spec:
  storageClassName: disk
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/pv6
