apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis-server

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: redis-server

  template:
    metadata:
      labels:
        app: redis-server

    spec:
      containers:
      - image: redis:latest
        name: redis
        ports:
        - containerPort: 6379

      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - redis-server
            topologyKey: zone

