kind: Pod
apiVersion: v1
metadata:
  name: test-pod
  labels:
    test: nfs-provisioner
spec:
  containers:
  - name: test-pod-dyn-storage
    image: mjbright/k8s-demo:alpine1

    #- "touch /mnt/SUCCESS && exit 0 || exit 1"
    command: ['/bin/sh', '-c', 'while true; do echo [host $(NODE_NAME)] [pod $(hostname)]: $(date) SUCCESS >> /mnt/SUCCESS; sleep 1; done']

    # Get NODE_NAME via downwardAPI - used in above command
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName

    volumeMounts:
      - name: nfs-pvc
        mountPath: "/mnt"

  volumes:
    - name: nfs-pvc
      persistentVolumeClaim:
        claimName: test-claim


