apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-testpod
spec:
  podSelector: {}
  ingress:
    - from:
        - podSelector:
            matchLabels:
              run: testpod
          namespaceSelector: {}
