apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts
spec:
  selector:
    matchLabels:
      app: test-sset # has to match .spec.template.metadata.labels
  serviceName: 'test-sset'

  replicas: 3

  template:
    metadata:
      labels:
        app: test-sset # has to match .spec.selector.matchLabels

    spec:
      #terminationGracePeriodSeconds: 10
      containers:
        - name: sset
          image: mjbright/k8s-demo:alpine2
          command: ['/bin/sh', '-c', '{ echo "------ container (re)start ----------"; while true; do echo [host $(NODE_NAME)] [pod $(hostname)]: $(date); sleep 1; done } >> /mnt/statefulset-date.log ']

          # Get NODE_NAME via downwardAPI - used in above command
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName

          ports:
            - containerPort: 80
              name: sset-port

          volumeMounts:
            - name: pvc-sts
              mountPath: /mnt

  volumeClaimTemplates:
    - metadata:
        name: pvc-sts
      spec:
        accessModes:
          - ReadWriteMany
        storageClassName: 'managed-nfs-storage'
        resources:
          requests:
            storage: 1Mi

