apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    run: flask-app

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      run: flask-app

  template:
    metadata:
      labels:
        run: flask-app

    spec:
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: Always
        name: flask-app
        ports:
        - containerPort: 5000

