apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    run: redis
    app.kubernetes.io/managed-by: Helm
  annotations:
      meta.helm.sh/release-name: v0.4
      meta.helm.sh/release-namespace: default

spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    run: redis
  type: LoadBalancer
status:
  loadBalancer: {}
