apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web

spec:
  replicas: 10
  selector:
    matchLabels:
      app: web

  template:
    metadata:
      labels:
        app: web

    spec:
      containers:
      - image: mjbright/k8s-demo:1
        name: k8s-demo

      nodeSelector:
        region: "0"

