apiVersion: v1
kind: Service

metadata:
  name: flask-db
  labels:
    app: flask-db

spec:
  type: ClusterIP

  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000

  selector:
    app: flask-db
