apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx
  name: nginx-nfs

spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx

  template:
    metadata:
      labels:
        run: nginx

    spec:
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - name: nfs-vol
          mountPath: /opt
        ports:
        - containerPort: 80
          protocol: TCP

      volumes:
      - name: nfs-vol
        persistentVolumeClaim:
          claimName: pvc-nfs
